### ISSUE TITLE
Operator == inconsistencies

### ISSUE THREAD

**Issue by josephmure** [openturns/openturns#1896]
A few examples discovered with @JPelamatti :

-----------------

```
In [49]: ot.Interval() == ot.ExpectationSimulationAlgorithm()
Out[49]: True
```
Possible explanation: Interval::operator == tries to use the DomainImplementation version https://github.com/openturns/openturns/blob/d6a14afe4954d6f35e7fe79481d918928a45935a/lib/src/Base/Geom/openturns/Interval.hxx#L111 

but it does not exist, so it falls back on the PersistentObject version, which for some reason always returns `true`.
This `using` line was introduced by PR https://github.com/openturns/openturns/pull/435

----------------

```
In [48]: ot.Interval() == ot.Sample([[1]])
Out[48]: False
```
Although the answer is technically correct, we would rather expect an exception. It looks like Sample::operator == falls back on the TypedInterfaceObject version.

https://github.com/openturns/openturns/blob/d6a14afe4954d6f35e7fe79481d918928a45935a/lib/src/Base/Stat/openturns/Sample.hxx#L111

----------------

```
In [50]: ot.Interval() != ot.Sample([[1]])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-50-e79ef30a885d> in <module>()
----> 1 ot.Interval() != ot.Sample([[1]])

/home/devel/GIT/openturns/build-master-doc/install/lib/python3.7/site-packages/openturns/typ.py in __ne__(self, other)
   9000 
   9001     def __ne__(self, other):
-> 9002         return _typ.Sample___ne__(self, other)
   9003 
   9004     def __baseaddress__(self):

TypeError: Object passed as argument is not convertible to a Sample
```

`Sample.hxx` has no `using` instruction for the operator `!=`, so it does not fall back to the TypedInterface version.

----------------

```
In [62]: ot.UsualRandomVector(ot.Normal())==ot.UsualRandomVector(ot.Laplace())
Out[62]: True

In [64]: ot.UsualRandomVector(ot.Normal())==ot.Laplace()
Out[64]: True
```

RandomVector does not implement the operator == and seems to fall back on the PermanentObject version. Note that we could easily compare the distributions: `ot.Laplace()==ot.Normal()` returns `false`.

----------------

```
In [65]: ot.Laplace()==ot.UsualRandomVector(ot.Normal())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-65-51b219b85369> in <module>()
----> 1 ot.Laplace()==ot.UsualRandomVector(ot.Normal())

/home/devel/GIT/openturns/build-master-doc/install/lib/python3.7/site-packages/openturns/dist_bundle2.py in __eq__(self, other)
   4671 
   4672     def __eq__(self, other):
-> 4673         return _dist_bundle2.Laplace___eq__(self, other)
   4674 
   4675     def __repr__(self):

TypeError: in method 'Laplace___eq__', argument 2 of type 'OT::Laplace const &'

```

When the `Laplace` distribution is the left object, it attempts to use its own implementation of the operator ==. With no `using` instruction in `Laplace.hxx`, it throws whenever the second argument is not of type `Laplace`.
